version: '3'
services:
  db:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: 'librarydb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'passwordroot'
      MYSQL_ROOT_HOST: '172.23.0.1'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: